import { rest } from 'msw';

export const handlers = [
  // GitHub Git Database Refenrence API
  // https://docs.github.com/en/rest/git/refs
  rest.get('https://api.github.com/repos/:owner/:repo/git/ref/*', (_req, res, ctx) =>
    res(
      ctx.status(200),
      ctx.json({
        ref: 'refs/heads/featureA',
        node_id: 'MDM6UmVmcmVmcy9oZWFkcy9mZWF0dXJlQQ==',
        url: 'https://api.github.com/repos/octocat/Hello-World/git/refs/heads/featureA',
        object: {
          type: 'commit',
          sha: 'aa218f56b14c9653891f9e74264a383fa43fefbd',
          url: 'https://api.github.com/repos/octocat/Hello-World/git/commits/aa218f56b14c9653891f9e74264a383fa43fefbd',
        },
      }),
    ),
  ),
  rest.post('https://api.github.com/repos/:owner/:repo/git/refs', (_req, res, ctx) =>
    res(
      ctx.status(200),
      ctx.json({
        ref: 'refs/heads/featureA',
        node_id: 'MDM6UmVmcmVmcy9oZWFkcy9mZWF0dXJlQQ==',
        url: 'https://api.github.com/repos/octocat/Hello-World/git/refs/heads/featureA',
        object: {
          type: 'commit',
          sha: 'aa218f56b14c9653891f9e74264a383fa43fefbd',
          url: 'https://api.github.com/repos/octocat/Hello-World/git/commits/aa218f56b14c9653891f9e74264a383fa43fefbd',
        },
      }),
    ),
  ),
  rest.delete('https://api.github.com/repos/:owner/:repo/git/refs/:refname', (_req, res, ctx) =>
    res(ctx.status(204)),
  ),

  // GitHub Git Database Commit API
  // https://docs.github.com/en/rest/git/commits
  rest.get('https://api.github.com/repos/:owner/:repo/git/commits/:hash', (_req, res, ctx) =>
    res(
      ctx.status(200),
      ctx.json({
        sha: '7638417db6d59f3c431d3e1f261cc637155684cd',
        node_id: 'MDY6Q29tbWl0NmRjYjA5YjViNTc4NzVmMzM0ZjYxYWViZWQ2OTVlMmU0MTkzZGI1ZQ==',
        url: 'https://api.github.com/repos/octocat/Hello-World/git/commits/7638417db6d59f3c431d3e1f261cc637155684cd',
        html_url:
          'https://github.com/octocat/Hello-World/commit/7638417db6d59f3c431d3e1f261cc637155684cd',
        author: {
          date: '2014-11-07T22:01:45Z',
          name: 'Monalisa Octocat',
          email: 'octocat@github.com',
        },
        committer: {
          date: '2014-11-07T22:01:45Z',
          name: 'Monalisa Octocat',
          email: 'octocat@github.com',
        },
        message: 'added readme, because im a good github citizen',
        tree: {
          url: 'https://api.github.com/repos/octocat/Hello-World/git/trees/691272480426f78a0138979dd3ce63b77f706feb',
          sha: '691272480426f78a0138979dd3ce63b77f706feb',
        },
        parents: [
          {
            url: 'https://api.github.com/repos/octocat/Hello-World/git/commits/1acc419d4d6a9ce985db7be48c6349a0475975b5',
            sha: '1acc419d4d6a9ce985db7be48c6349a0475975b5',
            html_url:
              'https://github.com/octocat/Hello-World/commit/7638417db6d59f3c431d3e1f261cc637155684cd',
          },
        ],
        verification: {
          verified: false,
          reason: 'unsigned',
          signature: null,
          payload: null,
        },
      }),
    ),
  ),
  rest.post('https://api.github.com/repos/:owner/:repo/git/commits', (_req, res, ctx) =>
    res(
      ctx.status(200),
      ctx.json({
        sha: '7638417db6d59f3c431d3e1f261cc637155684cd',
        node_id: 'MDY6Q29tbWl0NzYzODQxN2RiNmQ1OWYzYzQzMWQzZTFmMjYxY2M2MzcxNTU2ODRjZA==',
        url: 'https://api.github.com/repos/octocat/Hello-World/git/commits/7638417db6d59f3c431d3e1f261cc637155684cd',
        author: {
          date: '2014-11-07T22:01:45Z',
          name: 'Monalisa Octocat',
          email: 'octocat@github.com',
        },
        committer: {
          date: '2014-11-07T22:01:45Z',
          name: 'Monalisa Octocat',
          email: 'octocat@github.com',
        },
        message: 'my commit message',
        tree: {
          url: 'https://api.github.com/repos/octocat/Hello-World/git/trees/827efc6d56897b048c772eb4087f854f46256132',
          sha: '827efc6d56897b048c772eb4087f854f46256132',
        },
        parents: [
          {
            url: 'https://api.github.com/repos/octocat/Hello-World/git/commits/7d1b31e74ee336d15cbd21741bc88a537ed063a0',
            sha: '7d1b31e74ee336d15cbd21741bc88a537ed063a0',
            html_url:
              'https://github.com/octocat/Hello-World/commit/7d1b31e74ee336d15cbd21741bc88a537ed063a0',
          },
        ],
        verification: {
          verified: false,
          reason: 'unsigned',
          signature: null,
          payload: null,
        },
        html_url:
          'https://github.com/octocat/Hello-World/commit/7638417db6d59f3c431d3e1f261cc637155684cd',
      }),
    ),
  ),

  // GitHub Git Database Tree API
  // https://docs.github.com/en/rest/git/trees
  rest.get('https://api.github.com/repos/:owner/:repo/git/trees/:hash', (_req, res, ctx) =>
    res(
      ctx.status(200),
      ctx.json({
        sha: '9fb037999f264ba9a7fc6274d15fa3ae2ab98312',
        url: 'https://api.github.com/repos/octocat/Hello-World/trees/9fb037999f264ba9a7fc6274d15fa3ae2ab98312',
        tree: [
          {
            path: 'index.md',
            mode: '100644',
            type: 'blob',
            size: 30,
            sha: '44b4fc6d56897b048c772eb4087f854f46256132',
            url: 'https://api.github.com/repos/octocat/Hello-World/git/blobs/44b4fc6d56897b048c772eb4087f854f46256132',
          },
          {
            path: 'testpage',
            mode: '040000',
            type: 'tree',
            sha: 'f484d249c660418515fb01c2b9662073663c242e',
            url: 'https://api.github.com/repos/octocat/Hello-World/git/blobs/f484d249c660418515fb01c2b9662073663c242e',
          },
          {
            path: 'exec_file',
            mode: '100755',
            type: 'blob',
            size: 75,
            sha: '45b983be36b73c0788dc9cbcb76cbb80fc7bb057',
            url: 'https://api.github.com/repos/octocat/Hello-World/git/blobs/45b983be36b73c0788dc9cbcb76cbb80fc7bb057',
          },
        ],
        truncated: false,
      }),
    ),
  ),
  rest.post('https://api.github.com/repos/:owner/:repo/git/trees', (_req, res, ctx) =>
    res(
      ctx.status(200),
      ctx.json({
        sha: 'cd8274d15fa3ae2ab983129fb037999f264ba9a7',
        url: 'https://api.github.com/repos/octocat/Hello-World/trees/cd8274d15fa3ae2ab983129fb037999f264ba9a7',
        tree: [
          {
            path: 'file.rb',
            mode: '100644',
            type: 'blob',
            size: 132,
            sha: '7c258a9869f33c1e1e1f74fbb32f07c86cb5a75b',
            url: 'https://api.github.com/repos/octocat/Hello-World/git/blobs/7c258a9869f33c1e1e1f74fbb32f07c86cb5a75b',
          },
        ],
        truncated: true,
      }),
    ),
  ),

  // GitHub Git Database Blob API
  // https://docs.github.com/en/rest/git/blobs
  rest.get('https://api.github.com/repos/:owner/:repo/git/blobs/:filehash', (_req, res, ctx) =>
    res(
      ctx.status(200),
      ctx.json({
        content: 'Q29udGVudCBvZiB0aGUgYmxvYg==',
        encoding: 'base64',
        url: 'https://api.github.com/repos/octocat/example/git/blobs/3a0f86fb8db8eea7ccbb9a95f325ddbedfb25e15',
        sha: '3a0f86fb8db8eea7ccbb9a95f325ddbedfb25e15',
        size: 19,
        node_id: 'Q29udGVudCBvZiB0aGUgYmxvYg==',
      }),
    ),
  ),
  rest.post('https://api.github.com/repos/:owner/:repo/git/blobs', (_req, res, ctx) =>
    res(
      ctx.status(200),
      ctx.json({
        url: 'https://api.github.com/repos/octocat/example/git/blobs/3a0f86fb8db8eea7ccbb9a95f325ddbedfb25e15',
        sha: '3a0f86fb8db8eea7ccbb9a95f325ddbedfb25e15',
      }),
    ),
  ),

  // GitHub Pull API
  // https://docs.github.com/en/rest/pulls/pulls
  rest.get('https://api.github.com/repos/:owner/:repo/pulls/:pull_number', (_req, res, ctx) =>
    res(
      ctx.status(200),
      ctx.json({
        url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
        id: 1,
        node_id: 'MDExOlB1bGxSZXF1ZXN0MQ==',
        html_url: 'https://github.com/octocat/Hello-World/pull/1347',
        diff_url: 'https://github.com/octocat/Hello-World/pull/1347.diff',
        patch_url: 'https://github.com/octocat/Hello-World/pull/1347.patch',
        issue_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347',
        commits_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347/commits',
        review_comments_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347/comments',
        review_comment_url:
          'https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}',
        comments_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/comments',
        statuses_url:
          'https://api.github.com/repos/octocat/Hello-World/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e',
        number: 1347,
        state: 'open',
        locked: true,
        title: 'Amazing new feature',
        user: {
          login: 'octocat',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://github.com/images/error/octocat_happy.gif',
          gravatar_id: '',
          url: 'https://api.github.com/users/octocat',
          html_url: 'https://github.com/octocat',
          followers_url: 'https://api.github.com/users/octocat/followers',
          following_url: 'https://api.github.com/users/octocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
          organizations_url: 'https://api.github.com/users/octocat/orgs',
          repos_url: 'https://api.github.com/users/octocat/repos',
          events_url: 'https://api.github.com/users/octocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/octocat/received_events',
          type: 'User',
          site_admin: false,
        },
        body: 'Please pull these awesome changes in!',
        labels: [
          {
            id: 208045946,
            node_id: 'MDU6TGFiZWwyMDgwNDU5NDY=',
            url: 'https://api.github.com/repos/octocat/Hello-World/labels/bug',
            name: 'bug',
            description: "Something isn't working",
            color: 'f29513',
            default: true,
          },
        ],
        milestone: {
          url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1',
          html_url: 'https://github.com/octocat/Hello-World/milestones/v1.0',
          labels_url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1/labels',
          id: 1002604,
          node_id: 'MDk6TWlsZXN0b25lMTAwMjYwNA==',
          number: 1,
          state: 'open',
          title: 'v1.0',
          description: 'Tracking milestone for version 1.0',
          creator: {
            login: 'octocat',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/octocat_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/octocat',
            html_url: 'https://github.com/octocat',
            followers_url: 'https://api.github.com/users/octocat/followers',
            following_url: 'https://api.github.com/users/octocat/following{/other_user}',
            gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
            organizations_url: 'https://api.github.com/users/octocat/orgs',
            repos_url: 'https://api.github.com/users/octocat/repos',
            events_url: 'https://api.github.com/users/octocat/events{/privacy}',
            received_events_url: 'https://api.github.com/users/octocat/received_events',
            type: 'User',
            site_admin: false,
          },
          open_issues: 4,
          closed_issues: 8,
          created_at: '2011-04-10T20:09:31Z',
          updated_at: '2014-03-03T18:58:10Z',
          closed_at: '2013-02-12T13:22:01Z',
          due_on: '2012-10-09T23:39:01Z',
        },
        active_lock_reason: 'too heated',
        created_at: '2011-01-26T19:01:12Z',
        updated_at: '2011-01-26T19:01:12Z',
        closed_at: '2011-01-26T19:01:12Z',
        merged_at: '2011-01-26T19:01:12Z',
        merge_commit_sha: 'e5bd3914e2e596debea16f433f57875b5b90bcd6',
        assignee: {
          login: 'octocat',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://github.com/images/error/octocat_happy.gif',
          gravatar_id: '',
          url: 'https://api.github.com/users/octocat',
          html_url: 'https://github.com/octocat',
          followers_url: 'https://api.github.com/users/octocat/followers',
          following_url: 'https://api.github.com/users/octocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
          organizations_url: 'https://api.github.com/users/octocat/orgs',
          repos_url: 'https://api.github.com/users/octocat/repos',
          events_url: 'https://api.github.com/users/octocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/octocat/received_events',
          type: 'User',
          site_admin: false,
        },
        assignees: [
          {
            login: 'octocat',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/octocat_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/octocat',
            html_url: 'https://github.com/octocat',
            followers_url: 'https://api.github.com/users/octocat/followers',
            following_url: 'https://api.github.com/users/octocat/following{/other_user}',
            gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
            organizations_url: 'https://api.github.com/users/octocat/orgs',
            repos_url: 'https://api.github.com/users/octocat/repos',
            events_url: 'https://api.github.com/users/octocat/events{/privacy}',
            received_events_url: 'https://api.github.com/users/octocat/received_events',
            type: 'User',
            site_admin: false,
          },
          {
            login: 'hubot',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/hubot_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/hubot',
            html_url: 'https://github.com/hubot',
            followers_url: 'https://api.github.com/users/hubot/followers',
            following_url: 'https://api.github.com/users/hubot/following{/other_user}',
            gists_url: 'https://api.github.com/users/hubot/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/hubot/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/hubot/subscriptions',
            organizations_url: 'https://api.github.com/users/hubot/orgs',
            repos_url: 'https://api.github.com/users/hubot/repos',
            events_url: 'https://api.github.com/users/hubot/events{/privacy}',
            received_events_url: 'https://api.github.com/users/hubot/received_events',
            type: 'User',
            site_admin: true,
          },
        ],
        requested_reviewers: [
          {
            login: 'other_user',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/other_user_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/other_user',
            html_url: 'https://github.com/other_user',
            followers_url: 'https://api.github.com/users/other_user/followers',
            following_url: 'https://api.github.com/users/other_user/following{/other_user}',
            gists_url: 'https://api.github.com/users/other_user/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/other_user/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/other_user/subscriptions',
            organizations_url: 'https://api.github.com/users/other_user/orgs',
            repos_url: 'https://api.github.com/users/other_user/repos',
            events_url: 'https://api.github.com/users/other_user/events{/privacy}',
            received_events_url: 'https://api.github.com/users/other_user/received_events',
            type: 'User',
            site_admin: false,
          },
        ],
        requested_teams: [
          {
            id: 1,
            node_id: 'MDQ6VGVhbTE=',
            url: 'https://api.github.com/teams/1',
            html_url: 'https://github.com/orgs/github/teams/justice-league',
            name: 'Justice League',
            slug: 'justice-league',
            description: 'A great team.',
            privacy: 'closed',
            permission: 'admin',
            members_url: 'https://api.github.com/teams/1/members{/member}',
            repositories_url: 'https://api.github.com/teams/1/repos',
          },
        ],
        head: {
          label: 'octocat:new-topic',
          ref: 'new-topic',
          sha: '6dcb09b5b57875f334f61aebed695e2e4193db5e',
          user: {
            login: 'octocat',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/octocat_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/octocat',
            html_url: 'https://github.com/octocat',
            followers_url: 'https://api.github.com/users/octocat/followers',
            following_url: 'https://api.github.com/users/octocat/following{/other_user}',
            gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
            organizations_url: 'https://api.github.com/users/octocat/orgs',
            repos_url: 'https://api.github.com/users/octocat/repos',
            events_url: 'https://api.github.com/users/octocat/events{/privacy}',
            received_events_url: 'https://api.github.com/users/octocat/received_events',
            type: 'User',
            site_admin: false,
          },
          repo: {
            id: 1296269,
            node_id: 'MDEwOlJlcG9zaXRvcnkxMjk2MjY5',
            name: 'Hello-World',
            full_name: 'octocat/Hello-World',
            owner: {
              login: 'octocat',
              id: 1,
              node_id: 'MDQ6VXNlcjE=',
              avatar_url: 'https://github.com/images/error/octocat_happy.gif',
              gravatar_id: '',
              url: 'https://api.github.com/users/octocat',
              html_url: 'https://github.com/octocat',
              followers_url: 'https://api.github.com/users/octocat/followers',
              following_url: 'https://api.github.com/users/octocat/following{/other_user}',
              gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
              organizations_url: 'https://api.github.com/users/octocat/orgs',
              repos_url: 'https://api.github.com/users/octocat/repos',
              events_url: 'https://api.github.com/users/octocat/events{/privacy}',
              received_events_url: 'https://api.github.com/users/octocat/received_events',
              type: 'User',
              site_admin: false,
            },
            private: false,
            html_url: 'https://github.com/octocat/Hello-World',
            description: 'This your first repo!',
            fork: false,
            url: 'https://api.github.com/repos/octocat/Hello-World',
            archive_url: 'https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}',
            assignees_url: 'https://api.github.com/repos/octocat/Hello-World/assignees{/user}',
            blobs_url: 'https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}',
            branches_url: 'https://api.github.com/repos/octocat/Hello-World/branches{/branch}',
            collaborators_url:
              'https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}',
            comments_url: 'https://api.github.com/repos/octocat/Hello-World/comments{/number}',
            commits_url: 'https://api.github.com/repos/octocat/Hello-World/commits{/sha}',
            compare_url: 'https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}',
            contents_url: 'https://api.github.com/repos/octocat/Hello-World/contents/{+path}',
            contributors_url: 'https://api.github.com/repos/octocat/Hello-World/contributors',
            deployments_url: 'https://api.github.com/repos/octocat/Hello-World/deployments',
            downloads_url: 'https://api.github.com/repos/octocat/Hello-World/downloads',
            events_url: 'https://api.github.com/repos/octocat/Hello-World/events',
            forks_url: 'https://api.github.com/repos/octocat/Hello-World/forks',
            git_commits_url: 'https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}',
            git_refs_url: 'https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}',
            git_tags_url: 'https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}',
            git_url: 'git:github.com/octocat/Hello-World.git',
            issue_comment_url:
              'https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}',
            issue_events_url:
              'https://api.github.com/repos/octocat/Hello-World/issues/events{/number}',
            issues_url: 'https://api.github.com/repos/octocat/Hello-World/issues{/number}',
            keys_url: 'https://api.github.com/repos/octocat/Hello-World/keys{/key_id}',
            labels_url: 'https://api.github.com/repos/octocat/Hello-World/labels{/name}',
            languages_url: 'https://api.github.com/repos/octocat/Hello-World/languages',
            merges_url: 'https://api.github.com/repos/octocat/Hello-World/merges',
            milestones_url: 'https://api.github.com/repos/octocat/Hello-World/milestones{/number}',
            notifications_url:
              'https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}',
            pulls_url: 'https://api.github.com/repos/octocat/Hello-World/pulls{/number}',
            releases_url: 'https://api.github.com/repos/octocat/Hello-World/releases{/id}',
            ssh_url: 'git@github.com:octocat/Hello-World.git',
            stargazers_url: 'https://api.github.com/repos/octocat/Hello-World/stargazers',
            statuses_url: 'https://api.github.com/repos/octocat/Hello-World/statuses/{sha}',
            subscribers_url: 'https://api.github.com/repos/octocat/Hello-World/subscribers',
            subscription_url: 'https://api.github.com/repos/octocat/Hello-World/subscription',
            tags_url: 'https://api.github.com/repos/octocat/Hello-World/tags',
            teams_url: 'https://api.github.com/repos/octocat/Hello-World/teams',
            trees_url: 'https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}',
            clone_url: 'https://github.com/octocat/Hello-World.git',
            mirror_url: 'git:git.example.com/octocat/Hello-World',
            hooks_url: 'https://api.github.com/repos/octocat/Hello-World/hooks',
            svn_url: 'https://svn.github.com/octocat/Hello-World',
            homepage: 'https://github.com',
            language: null,
            forks_count: 9,
            stargazers_count: 80,
            watchers_count: 80,
            size: 108,
            default_branch: 'master',
            open_issues_count: 0,
            topics: ['octocat', 'atom', 'electron', 'api'],
            has_issues: true,
            has_projects: true,
            has_wiki: true,
            has_pages: false,
            has_downloads: true,
            archived: false,
            disabled: false,
            pushed_at: '2011-01-26T19:06:43Z',
            created_at: '2011-01-26T19:01:12Z',
            updated_at: '2011-01-26T19:14:43Z',
            permissions: {
              admin: false,
              push: false,
              pull: true,
            },
            allow_rebase_merge: true,
            temp_clone_token: 'ABTLWHOULUVAXGTRYU7OC2876QJ2O',
            allow_squash_merge: true,
            allow_merge_commit: true,
            allow_forking: true,
            forks: 123,
            open_issues: 123,
            license: {
              key: 'mit',
              name: 'MIT License',
              url: 'https://api.github.com/licenses/mit',
              spdx_id: 'MIT',
              node_id: 'MDc6TGljZW5zZW1pdA==',
            },
            watchers: 123,
          },
        },
        base: {
          label: 'octocat:master',
          ref: 'master',
          sha: '6dcb09b5b57875f334f61aebed695e2e4193db5e',
          user: {
            login: 'octocat',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/octocat_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/octocat',
            html_url: 'https://github.com/octocat',
            followers_url: 'https://api.github.com/users/octocat/followers',
            following_url: 'https://api.github.com/users/octocat/following{/other_user}',
            gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
            organizations_url: 'https://api.github.com/users/octocat/orgs',
            repos_url: 'https://api.github.com/users/octocat/repos',
            events_url: 'https://api.github.com/users/octocat/events{/privacy}',
            received_events_url: 'https://api.github.com/users/octocat/received_events',
            type: 'User',
            site_admin: false,
          },
          repo: {
            id: 1296269,
            node_id: 'MDEwOlJlcG9zaXRvcnkxMjk2MjY5',
            name: 'Hello-World',
            full_name: 'octocat/Hello-World',
            owner: {
              login: 'octocat',
              id: 1,
              node_id: 'MDQ6VXNlcjE=',
              avatar_url: 'https://github.com/images/error/octocat_happy.gif',
              gravatar_id: '',
              url: 'https://api.github.com/users/octocat',
              html_url: 'https://github.com/octocat',
              followers_url: 'https://api.github.com/users/octocat/followers',
              following_url: 'https://api.github.com/users/octocat/following{/other_user}',
              gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
              organizations_url: 'https://api.github.com/users/octocat/orgs',
              repos_url: 'https://api.github.com/users/octocat/repos',
              events_url: 'https://api.github.com/users/octocat/events{/privacy}',
              received_events_url: 'https://api.github.com/users/octocat/received_events',
              type: 'User',
              site_admin: false,
            },
            private: false,
            html_url: 'https://github.com/octocat/Hello-World',
            description: 'This your first repo!',
            fork: false,
            url: 'https://api.github.com/repos/octocat/Hello-World',
            archive_url: 'https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}',
            assignees_url: 'https://api.github.com/repos/octocat/Hello-World/assignees{/user}',
            blobs_url: 'https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}',
            branches_url: 'https://api.github.com/repos/octocat/Hello-World/branches{/branch}',
            collaborators_url:
              'https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}',
            comments_url: 'https://api.github.com/repos/octocat/Hello-World/comments{/number}',
            commits_url: 'https://api.github.com/repos/octocat/Hello-World/commits{/sha}',
            compare_url: 'https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}',
            contents_url: 'https://api.github.com/repos/octocat/Hello-World/contents/{+path}',
            contributors_url: 'https://api.github.com/repos/octocat/Hello-World/contributors',
            deployments_url: 'https://api.github.com/repos/octocat/Hello-World/deployments',
            downloads_url: 'https://api.github.com/repos/octocat/Hello-World/downloads',
            events_url: 'https://api.github.com/repos/octocat/Hello-World/events',
            forks_url: 'https://api.github.com/repos/octocat/Hello-World/forks',
            git_commits_url: 'https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}',
            git_refs_url: 'https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}',
            git_tags_url: 'https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}',
            git_url: 'git:github.com/octocat/Hello-World.git',
            issue_comment_url:
              'https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}',
            issue_events_url:
              'https://api.github.com/repos/octocat/Hello-World/issues/events{/number}',
            issues_url: 'https://api.github.com/repos/octocat/Hello-World/issues{/number}',
            keys_url: 'https://api.github.com/repos/octocat/Hello-World/keys{/key_id}',
            labels_url: 'https://api.github.com/repos/octocat/Hello-World/labels{/name}',
            languages_url: 'https://api.github.com/repos/octocat/Hello-World/languages',
            merges_url: 'https://api.github.com/repos/octocat/Hello-World/merges',
            milestones_url: 'https://api.github.com/repos/octocat/Hello-World/milestones{/number}',
            notifications_url:
              'https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}',
            pulls_url: 'https://api.github.com/repos/octocat/Hello-World/pulls{/number}',
            releases_url: 'https://api.github.com/repos/octocat/Hello-World/releases{/id}',
            ssh_url: 'git@github.com:octocat/Hello-World.git',
            stargazers_url: 'https://api.github.com/repos/octocat/Hello-World/stargazers',
            statuses_url: 'https://api.github.com/repos/octocat/Hello-World/statuses/{sha}',
            subscribers_url: 'https://api.github.com/repos/octocat/Hello-World/subscribers',
            subscription_url: 'https://api.github.com/repos/octocat/Hello-World/subscription',
            tags_url: 'https://api.github.com/repos/octocat/Hello-World/tags',
            teams_url: 'https://api.github.com/repos/octocat/Hello-World/teams',
            trees_url: 'https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}',
            clone_url: 'https://github.com/octocat/Hello-World.git',
            mirror_url: 'git:git.example.com/octocat/Hello-World',
            hooks_url: 'https://api.github.com/repos/octocat/Hello-World/hooks',
            svn_url: 'https://svn.github.com/octocat/Hello-World',
            homepage: 'https://github.com',
            language: null,
            forks_count: 9,
            stargazers_count: 80,
            watchers_count: 80,
            size: 108,
            default_branch: 'master',
            open_issues_count: 0,
            topics: ['octocat', 'atom', 'electron', 'api'],
            has_issues: true,
            has_projects: true,
            has_wiki: true,
            has_pages: false,
            has_downloads: true,
            archived: false,
            disabled: false,
            pushed_at: '2011-01-26T19:06:43Z',
            created_at: '2011-01-26T19:01:12Z',
            updated_at: '2011-01-26T19:14:43Z',
            permissions: {
              admin: false,
              push: false,
              pull: true,
            },
            allow_rebase_merge: true,
            temp_clone_token: 'ABTLWHOULUVAXGTRYU7OC2876QJ2O',
            allow_squash_merge: true,
            allow_merge_commit: true,
            forks: 123,
            open_issues: 123,
            license: {
              key: 'mit',
              name: 'MIT License',
              url: 'https://api.github.com/licenses/mit',
              spdx_id: 'MIT',
              node_id: 'MDc6TGljZW5zZW1pdA==',
            },
            watchers: 123,
          },
        },
        _links: {
          self: {
            href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
          },
          html: {
            href: 'https://github.com/octocat/Hello-World/pull/1347',
          },
          issue: {
            href: 'https://api.github.com/repos/octocat/Hello-World/issues/1347',
          },
          comments: {
            href: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/comments',
          },
          review_comments: {
            href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347/comments',
          },
          review_comment: {
            href: 'https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}',
          },
          commits: {
            href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347/commits',
          },
          statuses: {
            href: 'https://api.github.com/repos/octocat/Hello-World/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e',
          },
        },
        author_association: 'OWNER',
        auto_merge: null,
        draft: false,
        merged: false,
        mergeable: true,
        rebaseable: true,
        mergeable_state: 'clean',
        merged_by: {
          login: 'octocat',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://github.com/images/error/octocat_happy.gif',
          gravatar_id: '',
          url: 'https://api.github.com/users/octocat',
          html_url: 'https://github.com/octocat',
          followers_url: 'https://api.github.com/users/octocat/followers',
          following_url: 'https://api.github.com/users/octocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
          organizations_url: 'https://api.github.com/users/octocat/orgs',
          repos_url: 'https://api.github.com/users/octocat/repos',
          events_url: 'https://api.github.com/users/octocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/octocat/received_events',
          type: 'User',
          site_admin: false,
        },
        comments: 10,
        review_comments: 0,
        maintainer_can_modify: true,
        commits: 3,
        additions: 100,
        deletions: 3,
        changed_files: 5,
      }),
    ),
  ),
  rest.post('https://api.github.com/repos/:owner/:repo/pulls', (_req, res, ctx) =>
    res(
      ctx.status(201),
      ctx.json({
        url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
        id: 1,
        node_id: 'MDExOlB1bGxSZXF1ZXN0MQ==',
        html_url: 'https://github.com/octocat/Hello-World/pull/1347',
        diff_url: 'https://github.com/octocat/Hello-World/pull/1347.diff',
        patch_url: 'https://github.com/octocat/Hello-World/pull/1347.patch',
        issue_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347',
        commits_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347/commits',
        review_comments_url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347/comments',
        review_comment_url:
          'https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}',
        comments_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/comments',
        statuses_url:
          'https://api.github.com/repos/octocat/Hello-World/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e',
        number: 1347,
        state: 'open',
        locked: true,
        title: 'Amazing new feature',
        user: {
          login: 'octocat',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://github.com/images/error/octocat_happy.gif',
          gravatar_id: '',
          url: 'https://api.github.com/users/octocat',
          html_url: 'https://github.com/octocat',
          followers_url: 'https://api.github.com/users/octocat/followers',
          following_url: 'https://api.github.com/users/octocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
          organizations_url: 'https://api.github.com/users/octocat/orgs',
          repos_url: 'https://api.github.com/users/octocat/repos',
          events_url: 'https://api.github.com/users/octocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/octocat/received_events',
          type: 'User',
          site_admin: false,
        },
        body: 'Please pull these awesome changes in!',
        labels: [
          {
            id: 208045946,
            node_id: 'MDU6TGFiZWwyMDgwNDU5NDY=',
            url: 'https://api.github.com/repos/octocat/Hello-World/labels/bug',
            name: 'bug',
            description: "Something isn't working",
            color: 'f29513',
            default: true,
          },
        ],
        milestone: {
          url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1',
          html_url: 'https://github.com/octocat/Hello-World/milestones/v1.0',
          labels_url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1/labels',
          id: 1002604,
          node_id: 'MDk6TWlsZXN0b25lMTAwMjYwNA==',
          number: 1,
          state: 'open',
          title: 'v1.0',
          description: 'Tracking milestone for version 1.0',
          creator: {
            login: 'octocat',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/octocat_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/octocat',
            html_url: 'https://github.com/octocat',
            followers_url: 'https://api.github.com/users/octocat/followers',
            following_url: 'https://api.github.com/users/octocat/following{/other_user}',
            gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
            organizations_url: 'https://api.github.com/users/octocat/orgs',
            repos_url: 'https://api.github.com/users/octocat/repos',
            events_url: 'https://api.github.com/users/octocat/events{/privacy}',
            received_events_url: 'https://api.github.com/users/octocat/received_events',
            type: 'User',
            site_admin: false,
          },
          open_issues: 4,
          closed_issues: 8,
          created_at: '2011-04-10T20:09:31Z',
          updated_at: '2014-03-03T18:58:10Z',
          closed_at: '2013-02-12T13:22:01Z',
          due_on: '2012-10-09T23:39:01Z',
        },
        active_lock_reason: 'too heated',
        created_at: '2011-01-26T19:01:12Z',
        updated_at: '2011-01-26T19:01:12Z',
        closed_at: '2011-01-26T19:01:12Z',
        merged_at: '2011-01-26T19:01:12Z',
        merge_commit_sha: 'e5bd3914e2e596debea16f433f57875b5b90bcd6',
        assignee: {
          login: 'octocat',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://github.com/images/error/octocat_happy.gif',
          gravatar_id: '',
          url: 'https://api.github.com/users/octocat',
          html_url: 'https://github.com/octocat',
          followers_url: 'https://api.github.com/users/octocat/followers',
          following_url: 'https://api.github.com/users/octocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
          organizations_url: 'https://api.github.com/users/octocat/orgs',
          repos_url: 'https://api.github.com/users/octocat/repos',
          events_url: 'https://api.github.com/users/octocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/octocat/received_events',
          type: 'User',
          site_admin: false,
        },
        assignees: [
          {
            login: 'octocat',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/octocat_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/octocat',
            html_url: 'https://github.com/octocat',
            followers_url: 'https://api.github.com/users/octocat/followers',
            following_url: 'https://api.github.com/users/octocat/following{/other_user}',
            gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
            organizations_url: 'https://api.github.com/users/octocat/orgs',
            repos_url: 'https://api.github.com/users/octocat/repos',
            events_url: 'https://api.github.com/users/octocat/events{/privacy}',
            received_events_url: 'https://api.github.com/users/octocat/received_events',
            type: 'User',
            site_admin: false,
          },
          {
            login: 'hubot',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/hubot_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/hubot',
            html_url: 'https://github.com/hubot',
            followers_url: 'https://api.github.com/users/hubot/followers',
            following_url: 'https://api.github.com/users/hubot/following{/other_user}',
            gists_url: 'https://api.github.com/users/hubot/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/hubot/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/hubot/subscriptions',
            organizations_url: 'https://api.github.com/users/hubot/orgs',
            repos_url: 'https://api.github.com/users/hubot/repos',
            events_url: 'https://api.github.com/users/hubot/events{/privacy}',
            received_events_url: 'https://api.github.com/users/hubot/received_events',
            type: 'User',
            site_admin: true,
          },
        ],
        requested_reviewers: [
          {
            login: 'other_user',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/other_user_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/other_user',
            html_url: 'https://github.com/other_user',
            followers_url: 'https://api.github.com/users/other_user/followers',
            following_url: 'https://api.github.com/users/other_user/following{/other_user}',
            gists_url: 'https://api.github.com/users/other_user/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/other_user/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/other_user/subscriptions',
            organizations_url: 'https://api.github.com/users/other_user/orgs',
            repos_url: 'https://api.github.com/users/other_user/repos',
            events_url: 'https://api.github.com/users/other_user/events{/privacy}',
            received_events_url: 'https://api.github.com/users/other_user/received_events',
            type: 'User',
            site_admin: false,
          },
        ],
        requested_teams: [
          {
            id: 1,
            node_id: 'MDQ6VGVhbTE=',
            url: 'https://api.github.com/teams/1',
            html_url: 'https://github.com/orgs/github/teams/justice-league',
            name: 'Justice League',
            slug: 'justice-league',
            description: 'A great team.',
            privacy: 'closed',
            permission: 'admin',
            members_url: 'https://api.github.com/teams/1/members{/member}',
            repositories_url: 'https://api.github.com/teams/1/repos',
          },
        ],
        head: {
          label: 'octocat:new-topic',
          ref: 'new-topic',
          sha: '6dcb09b5b57875f334f61aebed695e2e4193db5e',
          user: {
            login: 'octocat',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/octocat_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/octocat',
            html_url: 'https://github.com/octocat',
            followers_url: 'https://api.github.com/users/octocat/followers',
            following_url: 'https://api.github.com/users/octocat/following{/other_user}',
            gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
            organizations_url: 'https://api.github.com/users/octocat/orgs',
            repos_url: 'https://api.github.com/users/octocat/repos',
            events_url: 'https://api.github.com/users/octocat/events{/privacy}',
            received_events_url: 'https://api.github.com/users/octocat/received_events',
            type: 'User',
            site_admin: false,
          },
          repo: {
            id: 1296269,
            node_id: 'MDEwOlJlcG9zaXRvcnkxMjk2MjY5',
            name: 'Hello-World',
            full_name: 'octocat/Hello-World',
            owner: {
              login: 'octocat',
              id: 1,
              node_id: 'MDQ6VXNlcjE=',
              avatar_url: 'https://github.com/images/error/octocat_happy.gif',
              gravatar_id: '',
              url: 'https://api.github.com/users/octocat',
              html_url: 'https://github.com/octocat',
              followers_url: 'https://api.github.com/users/octocat/followers',
              following_url: 'https://api.github.com/users/octocat/following{/other_user}',
              gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
              organizations_url: 'https://api.github.com/users/octocat/orgs',
              repos_url: 'https://api.github.com/users/octocat/repos',
              events_url: 'https://api.github.com/users/octocat/events{/privacy}',
              received_events_url: 'https://api.github.com/users/octocat/received_events',
              type: 'User',
              site_admin: false,
            },
            private: false,
            html_url: 'https://github.com/octocat/Hello-World',
            description: 'This your first repo!',
            fork: false,
            url: 'https://api.github.com/repos/octocat/Hello-World',
            archive_url: 'https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}',
            assignees_url: 'https://api.github.com/repos/octocat/Hello-World/assignees{/user}',
            blobs_url: 'https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}',
            branches_url: 'https://api.github.com/repos/octocat/Hello-World/branches{/branch}',
            collaborators_url:
              'https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}',
            comments_url: 'https://api.github.com/repos/octocat/Hello-World/comments{/number}',
            commits_url: 'https://api.github.com/repos/octocat/Hello-World/commits{/sha}',
            compare_url: 'https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}',
            contents_url: 'https://api.github.com/repos/octocat/Hello-World/contents/{+path}',
            contributors_url: 'https://api.github.com/repos/octocat/Hello-World/contributors',
            deployments_url: 'https://api.github.com/repos/octocat/Hello-World/deployments',
            downloads_url: 'https://api.github.com/repos/octocat/Hello-World/downloads',
            events_url: 'https://api.github.com/repos/octocat/Hello-World/events',
            forks_url: 'https://api.github.com/repos/octocat/Hello-World/forks',
            git_commits_url: 'https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}',
            git_refs_url: 'https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}',
            git_tags_url: 'https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}',
            git_url: 'git:github.com/octocat/Hello-World.git',
            issue_comment_url:
              'https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}',
            issue_events_url:
              'https://api.github.com/repos/octocat/Hello-World/issues/events{/number}',
            issues_url: 'https://api.github.com/repos/octocat/Hello-World/issues{/number}',
            keys_url: 'https://api.github.com/repos/octocat/Hello-World/keys{/key_id}',
            labels_url: 'https://api.github.com/repos/octocat/Hello-World/labels{/name}',
            languages_url: 'https://api.github.com/repos/octocat/Hello-World/languages',
            merges_url: 'https://api.github.com/repos/octocat/Hello-World/merges',
            milestones_url: 'https://api.github.com/repos/octocat/Hello-World/milestones{/number}',
            notifications_url:
              'https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}',
            pulls_url: 'https://api.github.com/repos/octocat/Hello-World/pulls{/number}',
            releases_url: 'https://api.github.com/repos/octocat/Hello-World/releases{/id}',
            ssh_url: 'git@github.com:octocat/Hello-World.git',
            stargazers_url: 'https://api.github.com/repos/octocat/Hello-World/stargazers',
            statuses_url: 'https://api.github.com/repos/octocat/Hello-World/statuses/{sha}',
            subscribers_url: 'https://api.github.com/repos/octocat/Hello-World/subscribers',
            subscription_url: 'https://api.github.com/repos/octocat/Hello-World/subscription',
            tags_url: 'https://api.github.com/repos/octocat/Hello-World/tags',
            teams_url: 'https://api.github.com/repos/octocat/Hello-World/teams',
            trees_url: 'https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}',
            clone_url: 'https://github.com/octocat/Hello-World.git',
            mirror_url: 'git:git.example.com/octocat/Hello-World',
            hooks_url: 'https://api.github.com/repos/octocat/Hello-World/hooks',
            svn_url: 'https://svn.github.com/octocat/Hello-World',
            homepage: 'https://github.com',
            language: null,
            forks_count: 9,
            stargazers_count: 80,
            watchers_count: 80,
            size: 108,
            default_branch: 'master',
            open_issues_count: 0,
            topics: ['octocat', 'atom', 'electron', 'api'],
            has_issues: true,
            has_projects: true,
            has_wiki: true,
            has_pages: false,
            has_downloads: true,
            archived: false,
            disabled: false,
            pushed_at: '2011-01-26T19:06:43Z',
            created_at: '2011-01-26T19:01:12Z',
            updated_at: '2011-01-26T19:14:43Z',
            permissions: {
              admin: false,
              push: false,
              pull: true,
            },
            allow_rebase_merge: true,
            temp_clone_token: 'ABTLWHOULUVAXGTRYU7OC2876QJ2O',
            allow_squash_merge: true,
            allow_merge_commit: true,
            allow_forking: true,
            forks: 123,
            open_issues: 123,
            license: {
              key: 'mit',
              name: 'MIT License',
              url: 'https://api.github.com/licenses/mit',
              spdx_id: 'MIT',
              node_id: 'MDc6TGljZW5zZW1pdA==',
            },
            watchers: 123,
          },
        },
        base: {
          label: 'octocat:master',
          ref: 'master',
          sha: '6dcb09b5b57875f334f61aebed695e2e4193db5e',
          user: {
            login: 'octocat',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/octocat_happy.gif',
            gravatar_id: '',
            url: 'https://api.github.com/users/octocat',
            html_url: 'https://github.com/octocat',
            followers_url: 'https://api.github.com/users/octocat/followers',
            following_url: 'https://api.github.com/users/octocat/following{/other_user}',
            gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
            organizations_url: 'https://api.github.com/users/octocat/orgs',
            repos_url: 'https://api.github.com/users/octocat/repos',
            events_url: 'https://api.github.com/users/octocat/events{/privacy}',
            received_events_url: 'https://api.github.com/users/octocat/received_events',
            type: 'User',
            site_admin: false,
          },
          repo: {
            id: 1296269,
            node_id: 'MDEwOlJlcG9zaXRvcnkxMjk2MjY5',
            name: 'Hello-World',
            full_name: 'octocat/Hello-World',
            owner: {
              login: 'octocat',
              id: 1,
              node_id: 'MDQ6VXNlcjE=',
              avatar_url: 'https://github.com/images/error/octocat_happy.gif',
              gravatar_id: '',
              url: 'https://api.github.com/users/octocat',
              html_url: 'https://github.com/octocat',
              followers_url: 'https://api.github.com/users/octocat/followers',
              following_url: 'https://api.github.com/users/octocat/following{/other_user}',
              gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
              organizations_url: 'https://api.github.com/users/octocat/orgs',
              repos_url: 'https://api.github.com/users/octocat/repos',
              events_url: 'https://api.github.com/users/octocat/events{/privacy}',
              received_events_url: 'https://api.github.com/users/octocat/received_events',
              type: 'User',
              site_admin: false,
            },
            private: false,
            html_url: 'https://github.com/octocat/Hello-World',
            description: 'This your first repo!',
            fork: false,
            url: 'https://api.github.com/repos/octocat/Hello-World',
            archive_url: 'https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}',
            assignees_url: 'https://api.github.com/repos/octocat/Hello-World/assignees{/user}',
            blobs_url: 'https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}',
            branches_url: 'https://api.github.com/repos/octocat/Hello-World/branches{/branch}',
            collaborators_url:
              'https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}',
            comments_url: 'https://api.github.com/repos/octocat/Hello-World/comments{/number}',
            commits_url: 'https://api.github.com/repos/octocat/Hello-World/commits{/sha}',
            compare_url: 'https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}',
            contents_url: 'https://api.github.com/repos/octocat/Hello-World/contents/{+path}',
            contributors_url: 'https://api.github.com/repos/octocat/Hello-World/contributors',
            deployments_url: 'https://api.github.com/repos/octocat/Hello-World/deployments',
            downloads_url: 'https://api.github.com/repos/octocat/Hello-World/downloads',
            events_url: 'https://api.github.com/repos/octocat/Hello-World/events',
            forks_url: 'https://api.github.com/repos/octocat/Hello-World/forks',
            git_commits_url: 'https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}',
            git_refs_url: 'https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}',
            git_tags_url: 'https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}',
            git_url: 'git:github.com/octocat/Hello-World.git',
            issue_comment_url:
              'https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}',
            issue_events_url:
              'https://api.github.com/repos/octocat/Hello-World/issues/events{/number}',
            issues_url: 'https://api.github.com/repos/octocat/Hello-World/issues{/number}',
            keys_url: 'https://api.github.com/repos/octocat/Hello-World/keys{/key_id}',
            labels_url: 'https://api.github.com/repos/octocat/Hello-World/labels{/name}',
            languages_url: 'https://api.github.com/repos/octocat/Hello-World/languages',
            merges_url: 'https://api.github.com/repos/octocat/Hello-World/merges',
            milestones_url: 'https://api.github.com/repos/octocat/Hello-World/milestones{/number}',
            notifications_url:
              'https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}',
            pulls_url: 'https://api.github.com/repos/octocat/Hello-World/pulls{/number}',
            releases_url: 'https://api.github.com/repos/octocat/Hello-World/releases{/id}',
            ssh_url: 'git@github.com:octocat/Hello-World.git',
            stargazers_url: 'https://api.github.com/repos/octocat/Hello-World/stargazers',
            statuses_url: 'https://api.github.com/repos/octocat/Hello-World/statuses/{sha}',
            subscribers_url: 'https://api.github.com/repos/octocat/Hello-World/subscribers',
            subscription_url: 'https://api.github.com/repos/octocat/Hello-World/subscription',
            tags_url: 'https://api.github.com/repos/octocat/Hello-World/tags',
            teams_url: 'https://api.github.com/repos/octocat/Hello-World/teams',
            trees_url: 'https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}',
            clone_url: 'https://github.com/octocat/Hello-World.git',
            mirror_url: 'git:git.example.com/octocat/Hello-World',
            hooks_url: 'https://api.github.com/repos/octocat/Hello-World/hooks',
            svn_url: 'https://svn.github.com/octocat/Hello-World',
            homepage: 'https://github.com',
            language: null,
            forks_count: 9,
            stargazers_count: 80,
            watchers_count: 80,
            size: 108,
            default_branch: 'master',
            open_issues_count: 0,
            topics: ['octocat', 'atom', 'electron', 'api'],
            has_issues: true,
            has_projects: true,
            has_wiki: true,
            has_pages: false,
            has_downloads: true,
            archived: false,
            disabled: false,
            pushed_at: '2011-01-26T19:06:43Z',
            created_at: '2011-01-26T19:01:12Z',
            updated_at: '2011-01-26T19:14:43Z',
            permissions: {
              admin: false,
              push: false,
              pull: true,
            },
            allow_rebase_merge: true,
            temp_clone_token: 'ABTLWHOULUVAXGTRYU7OC2876QJ2O',
            allow_squash_merge: true,
            allow_merge_commit: true,
            forks: 123,
            open_issues: 123,
            license: {
              key: 'mit',
              name: 'MIT License',
              url: 'https://api.github.com/licenses/mit',
              spdx_id: 'MIT',
              node_id: 'MDc6TGljZW5zZW1pdA==',
            },
            watchers: 123,
          },
        },
        _links: {
          self: {
            href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
          },
          html: {
            href: 'https://github.com/octocat/Hello-World/pull/1347',
          },
          issue: {
            href: 'https://api.github.com/repos/octocat/Hello-World/issues/1347',
          },
          comments: {
            href: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/comments',
          },
          review_comments: {
            href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347/comments',
          },
          review_comment: {
            href: 'https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}',
          },
          commits: {
            href: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347/commits',
          },
          statuses: {
            href: 'https://api.github.com/repos/octocat/Hello-World/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e',
          },
        },
        author_association: 'OWNER',
        auto_merge: null,
        draft: false,
        merged: false,
        mergeable: true,
        rebaseable: true,
        mergeable_state: 'clean',
        merged_by: {
          login: 'octocat',
          id: 1,
          node_id: 'MDQ6VXNlcjE=',
          avatar_url: 'https://github.com/images/error/octocat_happy.gif',
          gravatar_id: '',
          url: 'https://api.github.com/users/octocat',
          html_url: 'https://github.com/octocat',
          followers_url: 'https://api.github.com/users/octocat/followers',
          following_url: 'https://api.github.com/users/octocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
          organizations_url: 'https://api.github.com/users/octocat/orgs',
          repos_url: 'https://api.github.com/users/octocat/repos',
          events_url: 'https://api.github.com/users/octocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/octocat/received_events',
          type: 'User',
          site_admin: false,
        },
        comments: 10,
        review_comments: 0,
        maintainer_can_modify: true,
        commits: 3,
        additions: 100,
        deletions: 3,
        changed_files: 5,
      }),
    ),
  ),
  rest.put('https://api.github.com/repos/:owner/:repo/pulls/:pull_number/merge', (_req, res, ctx) =>
    res(
      ctx.status(200),
      ctx.json({
        sha: '6dcb09b5b57875f334f61aebed695e2e4193db5e',
        merged: true,
      }),
    ),
  ),

  // fallback handlers
  rest.get('*', (req, res, ctx) => {
    console.log(`Unhandled GET request: ${req.url.toString()}`);
    return res(ctx.status(500));
  }),
  rest.post('*', (req, res, ctx) => {
    console.log(`Unhandled POST request: ${req.url.toString()}`);
    return res(ctx.status(500));
  }),
  rest.put('*', (req, res, ctx) => {
    console.log(`Unhandled PUT request: ${req.url.toString()}`);
    return res(ctx.status(500));
  }),
];
