import { refractor } from 'refractor/lib/common';

import clike from 'refractor/lang/clike.js';
import c from 'refractor/lang/c.js';
import cpp from 'refractor/lang/cpp.js';
import arduino from 'refractor/lang/arduino.js';
import bash from 'refractor/lang/bash.js';
import csharp from 'refractor/lang/csharp.js';
import markup from 'refractor/lang/markup.js';
import css from 'refractor/lang/css.js';
import diff from 'refractor/lang/diff.js';
import go from 'refractor/lang/go.js';
import ini from 'refractor/lang/ini.js';
import java from 'refractor/lang/java.js';
import regex from 'refractor/lang/regex.js';
import javascript from 'refractor/lang/javascript.js';
import json from 'refractor/lang/json.js';
import kotlin from 'refractor/lang/kotlin.js';
import less from 'refractor/lang/less.js';
import lua from 'refractor/lang/lua.js';
import makefile from 'refractor/lang/makefile.js';
import yaml from 'refractor/lang/yaml.js';
import markdown from 'refractor/lang/markdown.js';
import objectivec from 'refractor/lang/objectivec.js';
import perl from 'refractor/lang/perl.js';
import markupTemplating from 'refractor/lang/markup-templating.js';
import php from 'refractor/lang/php.js';
import python from 'refractor/lang/python.js';
import r from 'refractor/lang/r.js';
import ruby from 'refractor/lang/ruby.js';
import rust from 'refractor/lang/rust.js';
import sass from 'refractor/lang/sass.js';
import scss from 'refractor/lang/scss.js';
import sql from 'refractor/lang/sql.js';
import swift from 'refractor/lang/swift.js';
import typescript from 'refractor/lang/typescript.js';
import basic from 'refractor/lang/basic.js';
import vbnet from 'refractor/lang/vbnet.js';

export { refractor };
refractor.register(clike);
refractor.register(c);
refractor.register(cpp);
refractor.register(arduino);
refractor.register(bash);
refractor.register(csharp);
refractor.register(markup);
refractor.register(css);
refractor.register(diff);
refractor.register(go);
refractor.register(ini);
refractor.register(java);
refractor.register(regex);
refractor.register(javascript);
refractor.register(json);
refractor.register(kotlin);
refractor.register(less);
refractor.register(lua);
refractor.register(makefile);
refractor.register(yaml);
refractor.register(markdown);
refractor.register(objectivec);
refractor.register(perl);
refractor.register(markupTemplating);
refractor.register(php);
refractor.register(python);
refractor.register(r);
refractor.register(ruby);
refractor.register(rust);
refractor.register(sass);
refractor.register(scss);
refractor.register(sql);
refractor.register(swift);
refractor.register(typescript);
refractor.register(basic);
refractor.register(vbnet);
