name: Lighthouse CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
        working-directory: ./example
      - run: npx lhci autorun
        working-directory: ./example
